### PR TITLE
Migrate tests to purescript-test-unit

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by garyb** [comment]
I'll merge this along with the query-representation update when that arrives. :wink: It's perhaps minorly breaking since the `show` instances have changed (for the better). 

Thanks!

**Comment by paluh** [comment]
I've changed query representation and fixed appropriate tests.

I only wonder If we want to differentiate between empty query (`Just (Query Nil))`) and completely missing query (`Nothing`)? Do you think that this difference could be semantically important?

**Comment by paluh** [comment]
I think that you should ignore my previous comment about query representation... I think that we really want to be exact here and reflect given url as close as possible in our values (so we want to catch this difference between missing and empty query). Am I right?

**Comment by garyb** [comment]
Yeah I think the distinction would be good to have. I'm not sure if semantically it would matter, but I guess the "visible" difference would be in the case of `Just (Query Nil)` you get a trailing `?` on the URL.

**Pull request merged**
