### PR TITLE
Next version

### PR DESCRIPTION
**Pull request by garyb**
- Fixes `URI` / `AbsoluteURI` representation to require `Scheme`
- Parametrises user info / path / query / fragment parts to allow for customised encoding/parsing
- Will switch to record representation for lenses-over-newtyped-records

### CODE REVIEW

**Comment by garyb** [comment]
Ok, this is done at last I think! It's basically a new library at this point, but it solves a lot of problems with the existing design, at the expense of being super picky (even more so than it was before) and involving a lot of type parameters. For most uses, I would expect library users would create fully-applied type synonyms of AbsoluteURI/URI/RelativeRef/URIRef with premade options records.

I think it should now be impossible to construct invalid (in the sense that they are un-parseable after printing) URIs too (aside from using the `unsafe` functions).

`IPv6Address` needs work, but it's no worse than it was before. With the new architecture it could be patched up externally too even, although it would be better to deal with it well in this library one day.

**Comment by garyb** [comment]
> Will switch to record representation for lenses-over-newtyped-records

This ended up not happening, as the main advantage was to be able to share some lenses between relative/hierarchical parts, etc. but some of these types are now sum types, so require `Traversal` definitions rather than the simple lenses they were previously.

**Comment by safareli** [comment]
Would be nice to add `{from,to}NEString` for `SegmentNE`

**Comment by safareli** [comment]
Also `Data.URI.Path` and some other types could be monoid or semigroups

**Comment by safareli** [comment]
README looks good 👍 
We can later add example using `Pathy` for segments too.

**Review by safareli — APPROVED** [review]

**Review by safareli — APPROVED** [review]

**Pull request merged**
