### PR TITLE
Remove warnings & add missing imports

### PR DESCRIPTION
**Pull request by chrisdotcode**

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Put on hold until v0.8 @garyb tells me.

**Comment by garyb** [comment]
Actually, I'll take this as it is. These changes are all still valid, we'll just need to do more later. Thanks!

**Comment by jonsterling** [comment]
Always :+1: for removing warnings!!

**Comment by chrisdotcode** [comment]
Don't forget to version++

**Pull request merged**
