### PR TITLE
Fix implementation of wrapParser

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes the issue discovered here: https://github.com/purescript/package-sets/pull/1075#issuecomment-1079430613=. Blocked by https://github.com/purescript-contrib/purescript-parsing/pull/166

I don't think this needs a changelog entry.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by natefaubion** [comment]
I don't think you need `runParserT'`, FWIW. This could be written with the exported representation.

**Comment by JordanMartinez** [comment]
> I don't think you need `runParserT'`, FWIW. This could be written with the exported representation.

How so?

**Comment by natefaubion** [comment]
It would be something like:

```purescript
wrapParser
  :: forall s m a b
   . (a -> Either URIPartParseError b)
  -> ParserT s m a
  -> ParserT s m b
wrapParser parseA (ParserT p) = ParserT
  ( mkFn5 \state1@(ParseState _ pos _) more lift throw done ->
      runFn5 p state1 more lift throw
        ( mkFn2 \state2 a ->
            case parseA a of
              Left (URIPartParseError err) ->
                runFn2 throw state2 (ParseError err pos)
              Right b ->
                runFn2 done b
        )
  )
```
Granted, this is a lot more complicated (as the internal rep is more complicated), but you don't need to incur any additional constraints or extra binds (you'll need MonadRec to runParserT). I'll leave that choice up to the maintainers.

**Comment by natefaubion** [comment]
Oh sorry, you don't even need that. The runParserT is completely unnecessary, since you can just use the state instances to achieve this.

**Comment by natefaubion** [comment]
```purescript
wrapParser
  :: forall s m a b
   . (a -> Either URIPartParseError b)
  -> ParserT s m a
  -> ParserT s m b
wrapParser parseA p = do
  ParseState _ pos _ <- get
  a <- p
  case parseA a of
    Left (URIPartParseError err) ->
      throwError (ParseError err pos)
    Right b ->
      pure b
```

**Comment by JordanMartinez** [comment]
Ah... So dropping the `ParserT do` and just running directly in the `ParserT` monad rather than what it newtypes.

**Comment by natefaubion** [comment]
Right, I'm not sure why it was written that way.

**Comment by JordanMartinez** [comment]
Well, can I get an approval, so I can merge this?

**Review by natefaubion — APPROVED** [review]

**Pull request merged**
